Backstop q4w exp
blend-capital/blend-ui pull request #162
Opened 2024-10-21 23:03 UTC by mootz12

* Update SDK to pull in fix for emissions estimation
* add ledger entry restore functionality for q4w
* add tooltips and cleanup tooltip usage
* patch visual bug in positions table

2024-10-21 23:04 UTC, mootz12 commented
Deployed to testnet UI

2024-10-21 23:15 UTC, drew-boy commented
APR tooltip doesn't need that comma, but it otherwise looks good

2024-10-21 23:16 UTC, drew-boy submitted a review, later dismissed
neat

2024-10-22 16:01 UTC, Ryang-21 requested changes

2024-10-22 16:01 UTC, Ryang-21 commented on src/components/backstop/BackstopQueueItem.tsx
> +    console.log('needsTooltip', needsTooltip);
logs

2024-10-22 16:28 UTC, drew-boy commented on src/components/backstop/BackstopQueueItem.tsx
> +    console.log('needsTooltip', needsTooltip);
change 'that' to 'which'

2024-10-22 16:58 UTC, Ryang-21 approved these changes

2024-10-22 17:02 UTC, merged