Feature/lp mint
blend-capital/blend-ui pull request #83
Opened 2024-02-14 20:50 UTC by carlosdimatteo

* new mint page
* new backstop page emissions and mint banners
* optional switch Button on inputBar
* debounce hook

2024-02-16 19:38 UTC, Ryang-21 commented on src/utils/comet.ts
> +      operation
Going to need to convert to xdr for change that occurred in blend sdk ie operation.toXDR('base64')

2024-02-16 20:43 UTC, carlosdimatteo commented on src/pages/backstop.tsx
> +  };
This codeblock is copied from https://github.com/blend-capital/blend-ui/blob/feature/LP-mint/src/components/dashboard/PositionOverview.tsx 
which is the claim emission button

2024-02-19 14:36 UTC, Ryang-21 commented on src/pages/backstop.tsx
> +      {!!userPoolData?.estimates?.totalEmissions && (
The backstop user estimates object from the blend-sdk contains an emissions attribute that can be checked for whether the user has emissions to be claimed and how much they have to claim

2024-02-19 14:42 UTC, Ryang-21 commented on src/pages/backstop.tsx
> +  };
The code for handling submission will be similar to this. We need to replace reserves token ids with the pool addresses that we are claiming. The pool addresses that a user is accumulating emissions for is stored in the backstop user object. The wallet.tsx file contains a BackstopClaim function which will be used instead.

2024-02-20 13:49 UTC, Ryang-21 requested changes
Looks pretty much there. Found a typo and then we should also load the user's Blend balance in the userslice.tsx

2024-02-20 13:49 UTC, Ryang-21 commented on src/utils/comet.ts
> +export interface competPoolGetDepositAmountByLPArgs {
typo

2024-02-22 20:02 UTC, Ryang-21 approved these changes
lgtm

2024-02-23 15:57 UTC, merged